/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.XChartPanel;
import bus.StatisticCustomer_BUS;
import gui.customchart.piechart.ModelPolarAreaChart;
import gui.customchart.piechart.PolarAreaChart;

/**
 *
 * @author Hoàng Khang
 */
public class StatisticCustomer_GUI extends javax.swing.JPanel {

    StatisticCustomer_BUS statisticCustomer_BUS = new StatisticCustomer_BUS();
    int data[] = statisticCustomer_BUS.filterCustomers();
    int numCus = statisticCustomer_BUS.getNumberCus();

    private final PolarAreaChart polarAreaChart = new PolarAreaChart();

    /**
     * Creates new form StatisticCustomer_GUI
     */
    public StatisticCustomer_GUI() {
        initComponents();
        initDataInfo();
        initPieChart();
    }

    public void initDataInfo() {
        txt_totalCustomer.setText(Integer.toString(statisticCustomer_BUS.sumCustomer()));

        txt_femaleUnder18.setText(Integer.toString(data[0]));
        txt_female18To40.setText(Integer.toString(data[1]));
        txt_femaleOver40.setText(Integer.toString(data[2]));
        txt_maleUnder18.setText(Integer.toString(data[3]));
        txt_male18To40.setText(Integer.toString(data[4]));
        txt_maleOver40.setText(Integer.toString(data[5]));
        txt_male.setText(Integer.toString(statisticCustomer_BUS.countMaleCustomers()));
        txt_female.setText(Integer.toString(statisticCustomer_BUS.sumCustomer() - statisticCustomer_BUS.countMaleCustomers()));

    }

    public void initPieChart() {

        // Create Chart
        polarAreaChart.setBackground(getBackground());

        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(129, 143, 180), "Nam dưới 18 tuổi", getRat(data[3])));

        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(230, 105, 62), "Nam từ 18 đến 40 tuổi", getRat(data[4])));
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(162, 197, 121), "Nam trên 40 tuổi", getRat(data[5])));
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(197, 168, 86), "Nữ dưới 18 tuổi", getRat(data[0])));
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(255, 223, 223), "Nữ từ 18 đến 40 tuổi", getRat(data[1])));
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(174, 222, 252), "Nữ trên 40 tuổi", getRat(data[2])));
        polarAreaChart.start();

    }

    public double getRat(int element) {
        return ((double) element / numCus) * 100;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_chart = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        pnl_infor = new javax.swing.JPanel();
        pnl_infoCustomer = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_totalCustomer = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_male = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_female = new javax.swing.JTextField();
        pnl_inforByGroup = new javax.swing.JPanel();
        pnl_groupOfMale = new javax.swing.JPanel();
        pnl_maleUnder18 = new javax.swing.JPanel();
        lbl_maleUnder18 = new javax.swing.JLabel();
        txt_maleUnder18 = new javax.swing.JTextField();
        pnl_male18To40 = new javax.swing.JPanel();
        lbl_male18To40 = new javax.swing.JLabel();
        txt_male18To40 = new javax.swing.JTextField();
        pnl_maleOver40 = new javax.swing.JPanel();
        lbl_maleOver40 = new javax.swing.JLabel();
        txt_maleOver40 = new javax.swing.JTextField();
        pnl_groupOfFemale = new javax.swing.JPanel();
        pnl_femaleUnder18 = new javax.swing.JPanel();
        lbl_femaleUnder18 = new javax.swing.JLabel();
        txt_femaleUnder18 = new javax.swing.JTextField();
        pnl_female18To40 = new javax.swing.JPanel();
        lbl_female18To40 = new javax.swing.JLabel();
        txt_female18To40 = new javax.swing.JTextField();
        pnl_femaleOver40 = new javax.swing.JPanel();
        lbl_femaleOver40 = new javax.swing.JLabel();
        txt_femaleOver40 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_chart.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê theo nhóm khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(71, 118, 185)), javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0))); // NOI18N
        pnl_chart.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_chart.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_chart.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_chart.setLayout(new javax.swing.BoxLayout(pnl_chart, javax.swing.BoxLayout.LINE_AXIS));
        add(pnl_chart, java.awt.BorderLayout.CENTER);
        pnl_chart.add(polarAreaChart);

        pnl_header.setLayout(new javax.swing.BoxLayout(pnl_header, javax.swing.BoxLayout.Y_AXIS));

        pnl_infor.setLayout(new javax.swing.BoxLayout(pnl_infor, javax.swing.BoxLayout.Y_AXIS));

        pnl_infoCustomer.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(71, 118, 185)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10))); // NOI18N
        pnl_infoCustomer.setMaximumSize(new java.awt.Dimension(2147483647, 14500));
        pnl_infoCustomer.setPreferredSize(new java.awt.Dimension(581, 120));
        pnl_infoCustomer.setLayout(new javax.swing.BoxLayout(pnl_infoCustomer, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel13.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jPanel13.setPreferredSize(new java.awt.Dimension(264, 100));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel14.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel14.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel14.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setFont(jLabel7.getFont().deriveFont((float)16));
        jLabel7.setText("Số lượng khách thành viên:");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanel14.add(jLabel7);

        txt_totalCustomer.setEditable(false);
        txt_totalCustomer.setFont(txt_totalCustomer.getFont().deriveFont((float)16));
        txt_totalCustomer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalCustomer.setToolTipText("");
        txt_totalCustomer.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_totalCustomer.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_totalCustomer.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_totalCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalCustomerActionPerformed(evt);
            }
        });
        jPanel14.add(txt_totalCustomer);

        jPanel13.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel15.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel15.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel15.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.X_AXIS));
        jPanel13.add(jPanel15);

        pnl_infoCustomer.add(jPanel13);

        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jPanel16.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jPanel16.setMinimumSize(new java.awt.Dimension(205, 100));
        jPanel16.setPreferredSize(new java.awt.Dimension(287, 100));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel17.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel17.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel17.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.X_AXIS));

        jLabel9.setFont(jLabel9.getFont().deriveFont((float)16));
        jLabel9.setText("Tổng khách nam:");
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanel17.add(jLabel9);

        txt_male.setEditable(false);
        txt_male.setFont(txt_male.getFont().deriveFont((float)16));
        txt_male.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_male.setText("t");
        txt_male.setToolTipText("");
        txt_male.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_male.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maleActionPerformed(evt);
            }
        });
        jPanel17.add(txt_male);

        jPanel16.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel18.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel18.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel18.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setFont(jLabel10.getFont().deriveFont((float)16));
        jLabel10.setText("Tổng khách nữ:");
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanel18.add(jLabel10);

        txt_female.setEditable(false);
        txt_female.setFont(txt_female.getFont().deriveFont((float)16));
        txt_female.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_female.setToolTipText("");
        txt_female.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_female.setMinimumSize(new java.awt.Dimension(64, 40));
        jPanel18.add(txt_female);

        jPanel16.add(jPanel18);

        pnl_infoCustomer.add(jPanel16);

        pnl_infor.add(pnl_infoCustomer);

        pnl_inforByGroup.setPreferredSize(new java.awt.Dimension(2934, 170));
        pnl_inforByGroup.setLayout(new java.awt.GridLayout(1, 2));

        pnl_groupOfMale.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách hàng nam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(71, 118, 185)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5))); // NOI18N
        pnl_groupOfMale.setMaximumSize(new java.awt.Dimension(152482, 200));
        pnl_groupOfMale.setLayout(new java.awt.GridLayout(3, 0));

        pnl_maleUnder18.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_maleUnder18.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_maleUnder18.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_maleUnder18.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_maleUnder18.setRequestFocusEnabled(false);
        pnl_maleUnder18.setLayout(new javax.swing.BoxLayout(pnl_maleUnder18, javax.swing.BoxLayout.X_AXIS));

        lbl_maleUnder18.setFont(lbl_maleUnder18.getFont().deriveFont((float)15));
        lbl_maleUnder18.setText("Nam < 18 tuổi:");
        lbl_maleUnder18.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_maleUnder18.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_maleUnder18.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_maleUnder18.add(lbl_maleUnder18);

        txt_maleUnder18.setEditable(false);
        txt_maleUnder18.setFont(txt_maleUnder18.getFont().deriveFont((float)16));
        txt_maleUnder18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_maleUnder18.setToolTipText("");
        txt_maleUnder18.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_maleUnder18.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_maleUnder18.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_maleUnder18.add(txt_maleUnder18);

        pnl_groupOfMale.add(pnl_maleUnder18);

        pnl_male18To40.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_male18To40.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_male18To40.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_male18To40.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_male18To40.setRequestFocusEnabled(false);
        pnl_male18To40.setLayout(new javax.swing.BoxLayout(pnl_male18To40, javax.swing.BoxLayout.X_AXIS));

        lbl_male18To40.setFont(lbl_male18To40.getFont().deriveFont((float)15));
        lbl_male18To40.setText("Nam từ 18 - 40 tuổi:");
        lbl_male18To40.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_male18To40.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_male18To40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_male18To40.add(lbl_male18To40);

        txt_male18To40.setEditable(false);
        txt_male18To40.setFont(txt_male18To40.getFont().deriveFont((float)16));
        txt_male18To40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_male18To40.setToolTipText("");
        txt_male18To40.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_male18To40.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_male18To40.setPreferredSize(new java.awt.Dimension(150, 40));
        txt_male18To40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_male18To40ActionPerformed(evt);
            }
        });
        pnl_male18To40.add(txt_male18To40);

        pnl_groupOfMale.add(pnl_male18To40);

        pnl_maleOver40.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_maleOver40.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_maleOver40.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_maleOver40.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_maleOver40.setRequestFocusEnabled(false);
        pnl_maleOver40.setLayout(new javax.swing.BoxLayout(pnl_maleOver40, javax.swing.BoxLayout.X_AXIS));

        lbl_maleOver40.setFont(lbl_maleOver40.getFont().deriveFont((float)15));
        lbl_maleOver40.setText("Nam > 40 tuổi");
        lbl_maleOver40.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_maleOver40.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_maleOver40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_maleOver40.add(lbl_maleOver40);

        txt_maleOver40.setEditable(false);
        txt_maleOver40.setFont(txt_maleOver40.getFont().deriveFont((float)16));
        txt_maleOver40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_maleOver40.setToolTipText("");
        txt_maleOver40.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_maleOver40.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_maleOver40.setPreferredSize(new java.awt.Dimension(150, 40));
        txt_maleOver40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maleOver40ActionPerformed(evt);
            }
        });
        pnl_maleOver40.add(txt_maleOver40);

        pnl_groupOfMale.add(pnl_maleOver40);

        pnl_inforByGroup.add(pnl_groupOfMale);

        pnl_groupOfFemale.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách hàng nữ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(71, 118, 185)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1))); // NOI18N
        pnl_groupOfFemale.setMaximumSize(new java.awt.Dimension(152482, 200));
        pnl_groupOfFemale.setMinimumSize(new java.awt.Dimension(46, 119));
        pnl_groupOfFemale.setPreferredSize(new java.awt.Dimension(1467, 119));
        pnl_groupOfFemale.setLayout(new java.awt.GridLayout(3, 0));

        pnl_femaleUnder18.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_femaleUnder18.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_femaleUnder18.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_femaleUnder18.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_femaleUnder18.setRequestFocusEnabled(false);
        pnl_femaleUnder18.setLayout(new javax.swing.BoxLayout(pnl_femaleUnder18, javax.swing.BoxLayout.X_AXIS));

        lbl_femaleUnder18.setFont(lbl_femaleUnder18.getFont().deriveFont((float)15));
        lbl_femaleUnder18.setText("Nữ < 18 tuổi:");
        lbl_femaleUnder18.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_femaleUnder18.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_femaleUnder18.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_femaleUnder18.add(lbl_femaleUnder18);

        txt_femaleUnder18.setEditable(false);
        txt_femaleUnder18.setFont(txt_femaleUnder18.getFont().deriveFont((float)16));
        txt_femaleUnder18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_femaleUnder18.setToolTipText("");
        txt_femaleUnder18.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_femaleUnder18.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_femaleUnder18.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_femaleUnder18.add(txt_femaleUnder18);

        pnl_groupOfFemale.add(pnl_femaleUnder18);

        pnl_female18To40.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_female18To40.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_female18To40.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_female18To40.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_female18To40.setRequestFocusEnabled(false);
        pnl_female18To40.setLayout(new javax.swing.BoxLayout(pnl_female18To40, javax.swing.BoxLayout.X_AXIS));

        lbl_female18To40.setFont(lbl_female18To40.getFont().deriveFont((float)15));
        lbl_female18To40.setText("Nữ từ 18 - 40 tuổi:");
        lbl_female18To40.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_female18To40.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_female18To40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_female18To40.add(lbl_female18To40);

        txt_female18To40.setEditable(false);
        txt_female18To40.setFont(txt_female18To40.getFont().deriveFont((float)16));
        txt_female18To40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_female18To40.setToolTipText("");
        txt_female18To40.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_female18To40.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_female18To40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_female18To40.add(txt_female18To40);

        pnl_groupOfFemale.add(pnl_female18To40);

        pnl_femaleOver40.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pnl_femaleOver40.setMaximumSize(new java.awt.Dimension(250000, 30));
        pnl_femaleOver40.setMinimumSize(new java.awt.Dimension(30, 30));
        pnl_femaleOver40.setPreferredSize(new java.awt.Dimension(1451, 30));
        pnl_femaleOver40.setRequestFocusEnabled(false);
        pnl_femaleOver40.setLayout(new javax.swing.BoxLayout(pnl_femaleOver40, javax.swing.BoxLayout.X_AXIS));

        lbl_femaleOver40.setFont(lbl_femaleOver40.getFont().deriveFont((float)15));
        lbl_femaleOver40.setText("Nữ > 40 tuổi:");
        lbl_femaleOver40.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_femaleOver40.setMinimumSize(new java.awt.Dimension(150, 40));
        lbl_femaleOver40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_femaleOver40.add(lbl_femaleOver40);

        txt_femaleOver40.setEditable(false);
        txt_femaleOver40.setFont(txt_femaleOver40.getFont().deriveFont((float)16));
        txt_femaleOver40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_femaleOver40.setToolTipText("");
        txt_femaleOver40.setMaximumSize(new java.awt.Dimension(22222222, 40));
        txt_femaleOver40.setMinimumSize(new java.awt.Dimension(2222222, 40));
        txt_femaleOver40.setPreferredSize(new java.awt.Dimension(150, 40));
        pnl_femaleOver40.add(txt_femaleOver40);

        pnl_groupOfFemale.add(pnl_femaleOver40);

        pnl_inforByGroup.add(pnl_groupOfFemale);

        pnl_infor.add(pnl_inforByGroup);

        pnl_header.add(pnl_infor);

        add(pnl_header, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maleOver40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maleOver40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maleOver40ActionPerformed

    private void txt_male18To40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_male18To40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_male18To40ActionPerformed

    private void txt_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maleActionPerformed

    private void txt_totalCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JLabel lbl_female18To40;
    private javax.swing.JLabel lbl_femaleOver40;
    private javax.swing.JLabel lbl_femaleUnder18;
    private javax.swing.JLabel lbl_male18To40;
    private javax.swing.JLabel lbl_maleOver40;
    private javax.swing.JLabel lbl_maleUnder18;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_female18To40;
    private javax.swing.JPanel pnl_femaleOver40;
    private javax.swing.JPanel pnl_femaleUnder18;
    private javax.swing.JPanel pnl_groupOfFemale;
    private javax.swing.JPanel pnl_groupOfMale;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_infoCustomer;
    private javax.swing.JPanel pnl_infor;
    private javax.swing.JPanel pnl_inforByGroup;
    private javax.swing.JPanel pnl_male18To40;
    private javax.swing.JPanel pnl_maleOver40;
    private javax.swing.JPanel pnl_maleUnder18;
    private javax.swing.JTextField txt_female;
    private javax.swing.JTextField txt_female18To40;
    private javax.swing.JTextField txt_femaleOver40;
    private javax.swing.JTextField txt_femaleUnder18;
    private javax.swing.JTextField txt_male;
    private javax.swing.JTextField txt_male18To40;
    private javax.swing.JTextField txt_maleOver40;
    private javax.swing.JTextField txt_maleUnder18;
    private javax.swing.JTextField txt_totalCustomer;
    // End of variables declaration//GEN-END:variables
}
