/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author thanhcanhit
 */
public class Welcome_GUI extends javax.swing.JFrame {

    private int value = 0;
    private static int dots = 0;

    /**
     * Creates new form Welcome_GUI
     */
    public Welcome_GUI() {
        initComponents();

//        Loading text animation
        new Timer(500, (ActionEvent evt) -> {
            dots++;
            if (dots > 3) {
                dots = 1;
            }

            String dotsString = "";
            for (int i = 0; i < dots; i++) {
                dotsString += ".";
            }
            lbl_loading.setText("Đang kết nối" + dotsString);
        }).start();

        Timer timer = new Timer(2500, (ActionEvent evt) -> {
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();

//        Loading bar animation
        new Timer(2, (ActionEvent evt) -> {
            if (value < 100) {
                value += 2;
                progressbar_status.setValue(value);
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_container = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_loading = new javax.swing.JLabel();
        pnl_decoration = new javax.swing.JPanel();
        pnl_decoration1 = new javax.swing.JPanel();
        pnl_decoration2 = new javax.swing.JPanel();
        progressbar_status = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 255));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnl_container.setMaximumSize(new java.awt.Dimension(400, 255));
        pnl_container.setMinimumSize(new java.awt.Dimension(400, 255));
        pnl_container.setPreferredSize(new java.awt.Dimension(400, 255));
        pnl_container.setLayout(null);

        lbl_header.setFont(lbl_header.getFont().deriveFont(lbl_header.getFont().getStyle() | java.awt.Font.BOLD, 32));
        lbl_header.setText("Omega Book");
        lbl_header.setIconTextGap(12);
        lbl_header.putClientProperty(FlatClientProperties.STYLE, "foreground:$Menu.foreground;");
        pnl_container.add(lbl_header);
        lbl_header.setBounds(100, 90, 240, 50);

        lbl_date.setFont(lbl_date.getFont().deriveFont(lbl_date.getFont().getStyle() | java.awt.Font.BOLD, 18));
        lbl_date.setText("10-2023");
        lbl_date.putClientProperty(FlatClientProperties.STYLE, "foreground:$Menu.foreground;");
        pnl_container.add(lbl_date);
        lbl_date.setBounds(320, 230, 80, 25);

        lbl_loading.setFont(lbl_loading.getFont().deriveFont((float)15));
        lbl_loading.setText("Đang kết nối...");
        lbl_loading.putClientProperty(FlatClientProperties.STYLE, "foreground:$Menu.foreground;");
        pnl_container.add(lbl_loading);
        lbl_loading.setBounds(150, 180, 94, 21);

        pnl_decoration.setBackground(new java.awt.Color(153, 204, 255));
        pnl_decoration.setForeground(new java.awt.Color(153, 204, 255));

        pnl_decoration.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decorationLayout = new javax.swing.GroupLayout(pnl_decoration);
        pnl_decoration.setLayout(pnl_decorationLayout);
        pnl_decorationLayout.setHorizontalGroup(
            pnl_decorationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_decorationLayout.setVerticalGroup(
            pnl_decorationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration);
        pnl_decoration.setBounds(-30, 120, 100, 100);

        pnl_decoration1.setBackground(new java.awt.Color(153, 204, 255));
        pnl_decoration1.setForeground(new java.awt.Color(153, 204, 255));

        pnl_decoration1.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration1Layout = new javax.swing.GroupLayout(pnl_decoration1);
        pnl_decoration1.setLayout(pnl_decoration1Layout);
        pnl_decoration1Layout.setHorizontalGroup(
            pnl_decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_decoration1Layout.setVerticalGroup(
            pnl_decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration1);
        pnl_decoration1.setBounds(320, 10, 50, 50);

        pnl_decoration2.setBackground(new java.awt.Color(153, 204, 255));
        pnl_decoration2.setForeground(new java.awt.Color(153, 204, 255));

        pnl_decoration2.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration2Layout = new javax.swing.GroupLayout(pnl_decoration2);
        pnl_decoration2.setLayout(pnl_decoration2Layout);
        pnl_decoration2Layout.setHorizontalGroup(
            pnl_decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnl_decoration2Layout.setVerticalGroup(
            pnl_decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration2);
        pnl_decoration2.setBounds(170, 230, 60, 60);

        progressbar_status.setValue(60);
        pnl_container.add(progressbar_status);
        progressbar_status.setBounds(90, 210, 240, 4);

        pnl_container.putClientProperty(FlatClientProperties.STYLE, "background:rgb(71, 118, 185);"
            + "arc:8;");

        getContentPane().add(pnl_container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_loading;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_decoration;
    private javax.swing.JPanel pnl_decoration1;
    private javax.swing.JPanel pnl_decoration2;
    private javax.swing.JProgressBar progressbar_status;
    // End of variables declaration//GEN-END:variables
}
